---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true

  roles:
    - role: azure_cli
    - role: wsl_colours
    - role: install_terraform
    - role: install_packer

  tasks:

    - name: Enable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Base utility packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - git
          - jq
          - jp
          - tree
          - figlet
          - stress
          - speedtest-cli
          - hugo
          - aha

    - name: Ansible .bashrc - root customisations
      blockinfile:
        path: ~/.bashrc
        block: |
          export EDITOR=vi
          alias ll='ls -l'
          set -o vi

    - name: Ansible .bashrc - jwt()
      blockinfile:
        path: ~{{ ansible_user_id }}/.bashrc
        block: |
          {% raw %}
          # Decode JWT tokens
          _decode_base64_url() {
            local len=$((${#1} % 4))
            local result="$1"
            if [ $len -eq 2 ]; then result="$1"'=='
            elif [ $len -eq 3 ]; then result="$1"'='
            fi
            echo "$result" | tr '_-' '/+' | base64 -d
          }

          # $1 => JWT to decode
          # $2 => either 1 for header or 2 for body (default is 2)
          jwt() { _decode_base64_url $(echo -n $1 | cut -d "." -f ${2:-2}) | jq .; }

          {% endraw %}
        marker: "# <!-- {mark} of Ansible automated JWT function -->"
        marker_begin: Start
        marker_end: End
        backup: yes

    - name: Ansible .bashrc - user customisations
      blockinfile:
        path: ~{{ ansible_user_id }}/.bashrc
        block: "{{ lookup('file', 'bashrc_user_customisations') }}"
        marker: "# <!-- {mark} of Ansible automated user customisations -->"
        marker_begin: Start
        marker_end: End
        backup: yes

    - name: Git config
      become: true
      become_user: richeney
      shell: |
        /usr/bin/git config --global user.email richeney@microsoft.com
        /usr/bin/git config --global user.name "Richard Cheney"
        /usr/bin/git config --global credential.user richeney
        /usr/bin/git config --global credential.helper store
        /usr/bin/git config --global init.defaultBranch main
        exit 0
      args:
        creates: ~{{ ansible_user_id }}/.gitconfig
